/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.KhoDao;
import POJO.Kho;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author quang
 */
public class KhoLayout extends javax.swing.JFrame {

    /**
     * Creates new form Kho
     */
    public KhoLayout() {
        initComponents();          
        loadTableData();

        //Tìm kiếm
       txtTimNguyenLieu.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchTable(txtTimNguyenLieu.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchTable(txtTimNguyenLieu.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                searchTable(txtTimNguyenLieu.getText());
            }  
    private void searchTable(String keyword) {
    ArrayList<POJO.Kho> dsPB = DAO.KhoDao.LayDanhSachKho();
    DefaultTableModel dtmBan = (DefaultTableModel) tblKho.getModel();
    dtmBan.setRowCount(0); // Xóa dữ liệu cũ từ bảng trước khi cập nhật với dữ liệu mới

    for (POJO.Kho pb : dsPB) {
        if (pb.getTenNguyenLieu().toLowerCase().contains(keyword.toLowerCase()) || 
            String.valueOf(pb.getMaNguyenLieu()).contains(keyword) || 
            pb.getDonViTinh().toLowerCase().contains(keyword.toLowerCase()) ||
            String.valueOf(pb.getSoLuongTon()).contains(keyword)) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(pb.getMaNguyenLieu());
            vec.add(pb.getTenNguyenLieu());
            vec.add(pb.getDonViTinh());
            vec.add(pb.getSoLuongTon());
            dtmBan.addRow(vec); // Thêm hàng mới vào bảng
        }
    }
}

        });
    }
    private void loadTableData() {
    ArrayList<POJO.Kho> dsPB = DAO.KhoDao.LayDanhSachKho();
    DefaultTableModel dtmBan = (DefaultTableModel) tblKho.getModel();
    dtmBan.setRowCount(0);
    double tongSoLuong = 0; // Khởi tạo biến tổng số lượng

    for (POJO.Kho pb : dsPB) {
        Vector<Object> vec = new Vector<Object>();
        vec.add(pb.getMaNguyenLieu());
        vec.add(pb.getTenNguyenLieu());
        vec.add(pb.getDonViTinh());
        vec.add(pb.getSoLuongTon());
        dtmBan.addRow(vec);
        tongSoLuong += pb.getSoLuongTon(); // Cộng dồn số lượng tồn
    }
    tblKho.setModel(dtmBan);

    // Cập nhật tổng số lượng nguyên liệu vào txtTongNL
    txtTongNL.setText(String.valueOf(tongSoLuong));
    
    tblKho.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent event) {
            // Check if row is selected
            if (!event.getValueIsAdjusting() && tblKho.getSelectedRow() != -1) {
                updateTextFields(tblKho.getSelectedRow());
            }
        }
    });
}
    private void updateTextFields(int selectedRow) {       
        DefaultTableModel dtmBan = (DefaultTableModel) tblKho.getModel();
        txtMaNL.setText(dtmBan.getValueAt(selectedRow, 0).toString()); // Cập nhật mã nhân viên
        txtTenNguyenLieu.setText(dtmBan.getValueAt(selectedRow, 1).toString());
        txtDonViTinh.setText(dtmBan.getValueAt(selectedRow, 2).toString());
        txtSoLuongTon.setText(dtmBan.getValueAt(selectedRow, 3).toString());       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTongNL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTimNguyenLieu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKho = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaNL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenNguyenLieu = new javax.swing.JTextField();
        txtDonViTinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSoLuongTon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btbThemMoi = new javax.swing.JButton();
        btnXuatKho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Remove-bg.ai_1716824396907.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/close(1).png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        btnTrangChu.setBackground(new java.awt.Color(0, 0, 0));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTrangChu.setText("TRANG CHỦ");
        btnTrangChu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangChujLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnTrangChu)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("QUẢN LÝ NGUYÊN LIỆU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("TỔNG SỐ NGUYÊN LIỆU");

        jLabel3.setText("DANH SÁCH NGUYÊN LIỆU");

        txtTimNguyenLieu.setBackground(new java.awt.Color(204, 204, 204));
        txtTimNguyenLieu.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtTimNguyenLieu.setText("Tìm kiếm nguyên liệu");
        txtTimNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimNguyenLieuActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/glass(1).png"))); // NOI18N
        jLabel4.setText("jLabel4");

        btnThem.setBackground(new java.awt.Color(255, 153, 153));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/plus(1).png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 153, 153));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/changes.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 255), null, null));
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 153, 153));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/bin(1)(1).png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 0, 51), null, null));
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NL", "Tên nguyên liệu", "Đơn vị tính", "Số lượng tồn"
            }
        ));
        jScrollPane1.setViewportView(tblKho);

        jLabel5.setText("Mã NL");

        txtMaNL.setEnabled(false);
        txtMaNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNLActionPerformed(evt);
            }
        });

        jLabel6.setText("Tên nguyên liệu");

        jLabel8.setText("Đơn vị tính");

        txtSoLuongTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongTonActionPerformed(evt);
            }
        });

        jLabel9.setText("Số lượng tồn");

        btbThemMoi.setBackground(new java.awt.Color(255, 153, 153));
        btbThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btbThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/plus(1).png"))); // NOI18N
        btbThemMoi.setText("Thêm mới");
        btbThemMoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        btbThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btbThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbThemMoiActionPerformed(evt);
            }
        });

        btnXuatKho.setBackground(new java.awt.Color(255, 153, 153));
        btnXuatKho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXuatKho.setText("Xuất kho");
        btnXuatKho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        btnXuatKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatKhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaNL, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(txtTenNguyenLieu)
                    .addComponent(txtDonViTinh)
                    .addComponent(txtSoLuongTon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btbThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXuatKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMaNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btbThemMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnXuatKho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongNL, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTongNL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtTimNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChujLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChujLabel6MouseClicked
       TrangChuQL trangChuQL = new TrangChuQL();
        trangChuQL.setVisible(true);
        this.dispose(); // Đóng MainFrame hiện tại
    }//GEN-LAST:event_btnTrangChujLabel6MouseClicked

    private void txtTimNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimNguyenLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimNguyenLieuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed


    //test
    int selectedRow = tblKho.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một mục trong kho!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Lấy mã nguyên liệu từ hàng được chọn
    int maNguyenLieu = (int) tblKho.getValueAt(selectedRow, 0);
    String tenNguyenLieu = (String) tblKho.getValueAt(selectedRow, 1);
    String donViTinh = (String) tblKho.getValueAt(selectedRow, 2);
    double soLuongTonHienTai = (double) tblKho.getValueAt(selectedRow, 3);

    // Hiển thị hộp thoại để nhập số lượng cần thêm
    String soLuongThemText = JOptionPane.showInputDialog(this, "Nhập số lượng cần thêm:");
    if (soLuongThemText == null || soLuongThemText.trim().isEmpty()) {
        return; // Người dùng nhấn Cancel hoặc không nhập gì
    }

    double soLuongThem;
    try {
        soLuongThem = Double.parseDouble(soLuongThemText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Cập nhật số lượng tồn
    double soLuongTonMoi = soLuongTonHienTai + soLuongThem;

    // Tạo đối tượng Kho và cập nhật số lượng tồn mới
    Kho kho = new Kho();
    kho.setMaNguyenLieu(maNguyenLieu);
    kho.setTenNguyenLieu(tenNguyenLieu);
    kho.setDonViTinh(donViTinh);
    kho.setSoLuongTon(soLuongTonMoi);

    // Thực hiện cập nhật vào cơ sở dữ liệu
    boolean thanhCong = KhoDao.capNhatKho(kho);
    if (thanhCong) {
        JOptionPane.showMessageDialog(this, "Cập nhật kho thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        loadTableData(); // Gọi phương thức loadTableData() để cập nhật bảng
    } else {
        JOptionPane.showMessageDialog(this, "Cập nhật kho thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        // Lấy chỉ mục của hàng được chọn
    int selectedRow = tblKho.getSelectedRow();
    if (selectedRow != -1) {
        // Lấy mã nguyên liệu từ cột đầu tiên của hàng được chọn
        int maNguyenLieu = Integer.parseInt(tblKho.getValueAt(selectedRow, 0).toString());
        
        // Gọi phương thức xóa từ lớp DAO
        boolean thanhCong = KhoDao.XoaKho(maNguyenLieu);

        // Hiển thị thông báo kết quả
        if (thanhCong) {
            JOptionPane.showMessageDialog(this, "Deleted successfully!");
            loadTableData(); // Tải lại dữ liệu của bảng
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to delete", "No Selection", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
              // TODO add your handling code here:
    int selectedRow = tblKho.getSelectedRow();
    if (selectedRow != -1) {
        DefaultTableModel dtmMonAn = (DefaultTableModel) tblKho.getModel();

        // Lấy dữ liệu từ các trường văn bản
        int maNL = Integer.parseInt(txtMaNL.getText());
        String tenNguyenLieu = txtTenNguyenLieu.getText();
        String donViTinh = txtDonViTinh.getText();
        double soLuongTon = Double.parseDouble(txtSoLuongTon.getText());
        
        // Kiểm tra các trường có rỗng hay không
        if (tenNguyenLieu.isEmpty() || donViTinh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy mã nguyên liệu từ hàng đã chọn
        int maNguyenLieu = Integer.parseInt(dtmMonAn.getValueAt(selectedRow, 0).toString());

        // Tạo đối tượng Kho và cập nhật các trường
        Kho kho = new Kho();
        kho.setMaNguyenLieu(maNguyenLieu); // Giữ nguyên mã nguyên liệu
        kho.setTenNguyenLieu(tenNguyenLieu);
        kho.setDonViTinh(donViTinh);
        kho.setSoLuongTon(soLuongTon);

        // Thực hiện cập nhật dữ liệu trong cơ sở dữ liệu
        boolean thanhCong = KhoDao.suaThongTinKho(kho);

        // Hiển thị thông báo kết quả
        if (thanhCong) {
            JOptionPane.showMessageDialog(this, "Updated successfully!");
            loadTableData(); // Tải lại dữ liệu của bảng
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a dish to edit", "No Selection", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMaNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNLActionPerformed

    private void txtSoLuongTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongTonActionPerformed

    private void btbThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbThemMoiActionPerformed
      //   TODO add your handling code here:
   // Lấy dữ liệu từ các trường nhập liệu
    String maNLText = txtMaNL.getText().trim();
    String tenNguyenLieu = txtTenNguyenLieu.getText().trim(); 
    String donViTinh = txtDonViTinh.getText().trim();
    String soLuongTonText = txtSoLuongTon.getText().trim();
        
    // Kiểm tra xem các trường có rỗng không
    if (tenNguyenLieu.isEmpty() || donViTinh.isEmpty() || soLuongTonText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }
    double soLuongTon;
    try {
        soLuongTon = Double.parseDouble(soLuongTonText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng tồn không hợp lệ!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Kiểm tra xem tên nguyên liệu đã tồn tại trong bảng hay chưa
    ArrayList<Kho> danhSachKho = KhoDao.LayDanhSachKho();
    for (Kho kho : danhSachKho) {
        if (kho.getTenNguyenLieu().equalsIgnoreCase(tenNguyenLieu)) {
            JOptionPane.showMessageDialog(this, "Tên nguyên liệu đã tồn tại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }

    // Tạo đối tượng Kho
    Kho kho = new Kho();
    kho.setTenNguyenLieu(tenNguyenLieu);
    kho.setDonViTinh(donViTinh);
    kho.setSoLuongTon(soLuongTon);

    // Thực hiện thêm vào cơ sở dữ liệu
    boolean thanhCong = KhoDao.ThemKho(kho);
    // Hiển thị thông báo kết quả
    if (thanhCong) {
        JOptionPane.showMessageDialog(this, "Thêm món thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        loadTableData(); // Gọi phương thức loadTableData() để cập nhật bảng
    } else {
        JOptionPane.showMessageDialog(this, "Thêm món thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btbThemMoiActionPerformed

    private void btnXuatKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatKhoActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblKho.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nguyên liệu cần xuất!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int maNguyenLieu = Integer.parseInt(tblKho.getValueAt(selectedRow, 0).toString());
    String tenNguyenLieu = tblKho.getValueAt(selectedRow, 1).toString();

    String soLuongXuatText = JOptionPane.showInputDialog(this, "Nhập số lượng cần xuất:");
    if (soLuongXuatText == null || soLuongXuatText.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Số lượng xuất không hợp lệ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    double soLuongXuat;
    try {
        soLuongXuat = Double.parseDouble(soLuongXuatText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng xuất không hợp lệ!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean thanhCong = KhoDao.XuatKho(maNguyenLieu, soLuongXuat);
    if (thanhCong) {
        JOptionPane.showMessageDialog(this, "Xuất kho thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        loadTableData(); // Cập nhật lại bảng kho
    } else {
        Kho kho = KhoDao.layKhoTheoMa(maNguyenLieu);
        if (kho != null && soLuongXuat > kho.getSoLuongTon()) {
            JOptionPane.showMessageDialog(this, "Số lượng xuất lớn hơn số lượng tồn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Xuất kho thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnXuatKhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
      

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbThemMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel btnTrangChu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatKho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblKho;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtMaNL;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTenNguyenLieu;
    private javax.swing.JTextField txtTimNguyenLieu;
    private javax.swing.JTextField txtTongNL;
    // End of variables declaration//GEN-END:variables
}
